package UI;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;

import java.awt.FlowLayout;

import javax.swing.SwingConstants;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.UIManager;

import java.awt.CardLayout;

import javax.swing.BoxLayout;

import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.GridLayout;
import java.lang.reflect.Array;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.AbstractAction;
import javax.swing.Action;

import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user1
 */
public class fq1 extends javax.swing.JFrame {

    /**
     * Creates new form fq1
     */
    public fq1() {
        initComponents();
        addTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista e Tavolinave");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 2, 18)); // NOI18N
        jLabel1.setText("Lista e Tavolinave");

        jPanel1.setName("tabPanel"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fq1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fq1().setVisible(true);
            }
        });
    }

    public void addTable()
    {
        //Button
        JButton but1 = new JButton("Tavolina Nr.1");
        JButton but2 = new JButton("Tavolina Nr.2");
        JButton but3 = new JButton("Tavolina Nr.3");
        JButton but4 = new JButton("Tavolina Nr.4");
        JButton but5 = new JButton("Tavolina Nr.5");
        JButton but6 = new JButton("Tavolina Nr.6");
        JButton but7 = new JButton("Tavolina Nr.7");
        JButton but8 = new JButton("Tavolina Nr.8");
        JButton but9 = new JButton("Tavolina Nr.9");
        JButton but10 = new JButton("Tavolina Nr.10");
        JButton but11 = new JButton("Tavolina Nr.11");
        JButton but12 = new JButton("Tavolina Nr.12");
 

//vendosja e ngjyrave tek butonat

        but1.setBackground(new java.awt.Color(85,163,132));
        but2.setBackground(new java.awt.Color(85,163,132));
        but3.setBackground(new java.awt.Color(85,163,132));
        but4.setBackground(new java.awt.Color(85,163,132));
        but5.setBackground(new java.awt.Color(85,163,132));
        but6.setBackground(new java.awt.Color(85,163,132));
        but7.setBackground(new java.awt.Color(85,163,132));
        but8.setBackground(new java.awt.Color(85,163,132));
        but9.setBackground(new java.awt.Color(85,163,132));
        but10.setBackground(new java.awt.Color(85,163,132));
        but11.setBackground(new java.awt.Color(85,163,132));
        but12.setBackground(new java.awt.Color(85,163,132));
    
  



//Button Layout
        but1.setBounds(1, 10, 100, 50);
        but2.setBounds(3, 80, 100, 50);
        but3.setBounds(5, 150, 100, 50);
        but4.setBounds(7, 220, 100, 50);
        but5.setBounds(110, 10, 100, 50 );   
        but6.setBounds(107, 80, 100, 50);
        but7.setBounds(107, 150, 100, 50);
        but8.setBounds(108, 220, 100, 50);
        but9.setBounds(218, 10, 110, 50);
        but10.setBounds(218, 80, 110, 50 );
        but11.setBounds(218, 150, 110, 50);
        but12.setBounds(218, 220, 110, 50);
        
   

//vendosim butonate te Paneli1
        jPanel1.add(but1);
        jPanel1.add(but2);
        jPanel1.add(but3);
        jPanel1.add(but4);
        jPanel1.add(but5);
        jPanel1.add(but6);
        jPanel1.add(but7);
        jPanel1.add(but8);
        jPanel1.add(but9);
        jPanel1.add(but10);
        jPanel1.add(but11);
        jPanel1.add(but12);
       
  
         pack();
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}